In [ ]:
import numpy as np
import torch

In [ ]:
# (temp,rainfall,humidity)
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]],dtype='float32')

In [ ]:
# target (apples,oranges)
targets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]],dtype='float32')

In [ ]:
# convert inputs and targets to tensor
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.0459,  1.6990, -0.1741],
        [ 0.1189,  1.1848,  2.2498]], requires_grad=True)
tensor([-0.2375,  1.4656], requires_grad=True)


In [ ]:
# model
def model(x):
  return x @ w.t() + b

In [ ]:
preds=model(inputs)
print(preds)

tensor([[102.7557, 186.2642],
        [133.9516, 260.5296],
        [213.3342, 301.0555],
        [ 61.6919, 147.7780],
        [147.5098, 280.8914]], grad_fn=<AddBackward0>)


In [ ]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# mse function
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

In [ ]:
mean_square_error=mse(preds,targets)
print(mean_square_error)

tensor(12313.5771, grad_fn=<DivBackward0>)


In [ ]:
# compute gradients
mean_square_error.backward()

In [ ]:
# gradient for weights and biases
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[-0.0459,  1.6990, -0.1741],
        [ 0.1189,  1.1848,  2.2498]], requires_grad=True)
tensor([[ 4711.7168,  5282.5693,  3091.0134],
        [12019.0352, 12930.5547,  8077.5317]])
tensor([-0.2375,  1.4656], requires_grad=True)
tensor([ 55.6486, 143.3038])


In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
preds=model(inputs)
print(preds)

tensor([[102.7557, 186.2642],
        [133.9516, 260.5296],
        [213.3342, 301.0555],
        [ 61.6919, 147.7780],
        [147.5098, 280.8914]], grad_fn=<AddBackward0>)


In [ ]:
# compute loss
loss=mse(preds,targets)
print(loss)

tensor(12313.5771, grad_fn=<DivBackward0>)


In [ ]:
# compute gradient
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 4711.7168,  5282.5693,  3091.0134],
        [12019.0352, 12930.5547,  8077.5317]])
tensor([ 55.6486, 143.3038])


In [ ]:
# adjust weights and reset gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[-9.3058e-02,  1.6462e+00, -2.0501e-01],
        [-1.3177e-03,  1.0555e+00,  2.1690e+00]], requires_grad=True)
tensor([-0.2381,  1.4642], requires_grad=True)


In [ ]:
# calculate loss
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(8338.6270, grad_fn=<DivBackward0>)


In [ ]:
# Train for 100 epochs
for i in range(100):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
# compute loss
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(95.4740, grad_fn=<DivBackward0>)


In [ ]:
# predicition
preds

tensor([[ 57.0573,  69.6816],
        [ 74.2781, 106.5660],
        [136.8983, 120.5627],
        [ 19.8969,  32.5887],
        [ 88.7708, 132.2652]], grad_fn=<AddBackward0>)

In [ ]:
# target
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# **Linear regression using pytorch built-ins**

In [ ]:
import torch.nn as nn

In [ ]:
# inputs (temps,rainfall,hum)
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70],
                 [74,66,43],
                 [91,87,65],
                 [88,134,59],
                 [101,44,37],
                 [68,96,71],
                 [73,66,44],
                 [92,87,64],
                 [87,135,57],
                 [103,43,36],
                 [68,97,70]],dtype='float32')
# targets(apples,oranges)
targets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119],
                  [57,69],
                  [80,102],
                  [118,132],
                  [21,38],
                  [104,118],
                  [57,69],
                  [82,100],
                  [118,134],
                  [20,38],
                  [102,120]],dtype='float32')

In [ ]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
# dataset and dataloader
from torch.utils.data import TensorDataset


In [ ]:
train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)


In [ ]:
for xb,yb,in train_dl:
  print(xb)
  print(yb)
  break

tensor([[103.,  43.,  36.],
        [ 73.,  66.,  44.],
        [ 74.,  66.,  43.],
        [ 69.,  96.,  70.],
        [101.,  44.,  37.]])
tensor([[ 20.,  38.],
        [ 57.,  69.],
        [ 57.,  69.],
        [103., 119.],
        [ 21.,  38.]])


In [ ]:
# model
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.1953,  0.4658, -0.3480],
        [ 0.3019,  0.1968,  0.2795]], requires_grad=True)
Parameter containing:
tensor([-0.5100,  0.0447], requires_grad=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1953,  0.4658, -0.3480],
         [ 0.3019,  0.1968,  0.2795]], requires_grad=True),
 Parameter containing:
 tensor([-0.5100,  0.0447], requires_grad=True)]

In [ ]:
preds=model(inputs)
preds

tensor([[  1.4795,  47.2854],
        [  0.4389,  62.7218],
        [ 24.7372,  68.8897],
        [-13.2780,  49.6389],
        [  6.3754,  59.3325],
        [  0.8183,  47.3905],
        [ -0.3749,  62.8045],
        [ 24.1939,  69.4711],
        [-12.6168,  49.5339],
        [  6.2228,  59.3102],
        [  0.6657,  47.3682],
        [ -0.2223,  62.8268],
        [ 25.5510,  68.8069],
        [-13.1253,  49.6612],
        [  7.0366,  59.2275]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
# compute mse
import torch.nn.functional as F

In [ ]:
loss_fn=F.mse_loss

In [ ]:
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(3862.0938, grad_fn=<MseLossBackward0>)


In [ ]:
# define optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [ ]:
# utility function to train the model
def fit(num_epochs,model,loss_fn,opt,train_dl):
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred=model(xb)
      loss=loss_fn(pred,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
  if (epoch+1)%10==0:
    print('Epoch [{}/{}],Loss:{:.4f}'.format(epoch+1,num_epochs,loss.item()))

In [ ]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [100/100],Loss:34.6640


In [ ]:
preds=model(inputs)
preds

tensor([[ 57.8439,  71.6599],
        [ 78.0601,  98.9510],
        [125.3973, 134.3574],
        [ 26.3531,  44.8291],
        [ 91.6483, 111.6203],
        [ 56.6056,  70.7083],
        [ 77.1525,  98.6849],
        [125.3036, 134.8066],
        [ 27.5914,  45.7806],
        [ 91.9790, 112.3057],
        [ 56.9363,  71.3938],
        [ 76.8218,  97.9995],
        [126.3048, 134.6234],
        [ 26.0224,  44.1436],
        [ 92.8866, 112.5718]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
model(torch.tensor([[75,63,44.]]))

tensor([[53.4337, 68.6573]], grad_fn=<AddmmBackward0>)