In [ ]:
!pip install torch numpy --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 19.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 14.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 13.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 45.9 MB/s eta 0:00:00


In [ ]:
import torch
import numpy as np

In [ ]:
t1=torch.tensor(4)

In [ ]:
t1

tensor(4)

In [ ]:
t1.dtype

torch.int64

In [ ]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
t2.dtype

torch.float32

In [ ]:
# Matrix
t3=torch.tensor([[5.,6],
                  [7,8],
                  [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
print(t1.shape)
print(t2.shape)
print(t3.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])


In [ ]:
# random tensor
rand_tensor = torch.rand(3, 3)  # 3x3 matrix with random values
print(rand_tensor)


tensor([[0.9950, 0.5352, 0.9831],
        [0.7395, 0.1048, 0.3997],
        [0.9288, 0.0383, 0.1764]])


In [ ]:
# tensor of zeros and ones
zeros = torch.zeros(2, 2)  # 2x2 matrix filled with zeros
ones = torch.ones(2, 2)    # 2x2 matrix filled with ones
print(zeros)
print(ones)


tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


#**Tensor operation and gradients**

In [ ]:
# addition and substraction,multiplication
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])


c = a + b
print(c)


c = torch.add(a, b)
print(c)

d = a - b
print(d)

d = torch.sub(a, b)
print(d)
# Create 2D matrices
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication using @ operator
C = A @ B
print(C)


tensor([5, 7, 9])
tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([-3, -3, -3])
tensor([[19, 22],
        [43, 50]])


In [ ]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# Arithmethic operations
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# compute derivatives
y.backward()

In [ ]:
# Display gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [ ]:
#➤ Creating a Tensor with Autograd Enabled
x = torch.tensor(2.0, requires_grad=True)
print(x)  # tensor(2., requires_grad=True)
y = x**2 + 3*x + 5  # Define function
y.backward()        # Compute gradient

# Print gradient (dy/dx)
print(x.grad)


tensor(2., requires_grad=True)
tensor(7.)


In [ ]:
# vector and matrices
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# Define function: sum of squares
y = x**2

# Compute gradients
y.sum().backward()

# Print gradients
print(x.grad)

tensor([2., 4., 6.])


In [ ]:
# stopping gradient computation
with torch.no_grad():
    z = x * 2
    print(z)  # No gradient tracking

tensor([2., 4., 6.])


In [ ]:
# numpy
import numpy as np
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
# convert the numpy array to a torch tensor
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [ ]:
x.dtype,y.dtype

(dtype('int64'), torch.int64)

In [ ]:
# convert a torch tensor to numpy array
z=y.numpy()
z

array([[1, 2],
       [3, 4]])

In [ ]:
 #Reshaping Tensors
 x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshape to 3x2
reshaped_x = x.view(3, 2)
print(reshaped_x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# ➤ Slicing and Indexing (Accessing Tensor Elements)
x = torch.tensor([[10, 20, 30], [40, 50, 60]])

# Access first row
print(x[0])  # tensor([10, 20, 30])

# Access first element of second row
print(x[1, 0])  # 40

# Get all rows but only first column
print(x[:, 0])  # tensor([10, 40])


tensor([10, 20, 30])
tensor(40)
tensor([10, 40])


In [ ]:
#➤ Moving Tensor to GPU (for Faster Computation)
# Check if GPU is available
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create tensor and move it to GPU
tensor_gpu = torch.tensor([1, 2, 3]).to(device)
print(tensor_gpu)


tensor([1, 2, 3])
