In [ ]:
import torch
import torch.nn as nn


In [ ]:
class Model(nn.Module):
    def __init__(self,num_features):
        super(Model, self).__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        return self.sigmoid(self.linear(features))


In [ ]:
features=torch.randn(10,5)
model=Model(features.shape[1])
model(features)

tensor([[0.5493],
        [0.6380],
        [0.3002],
        [0.5375],
        [0.4819],
        [0.4069],
        [0.5895],
        [0.6636],
        [0.5635],
        [0.5744]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.0275,  0.1180, -0.3743,  0.2833, -0.0362]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.1020], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

In [ ]:
# for 1 hidden layer with 3 node
class Model1(nn.Module):
    def __init__(self,num_features):
        super(Model1, self).__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self,features):
        return self.sigmoid(self.linear2(self.relu(self.linear1(features))))

In [ ]:
model1=Model1(features.shape[1])
model1(features)

tensor([[0.6296],
        [0.6428],
        [0.7022],
        [0.6050],
        [0.6820],
        [0.6012],
        [0.5915],
        [0.6100],
        [0.6975],
        [0.5595]], grad_fn=<SigmoidBackward0>)

In [ ]:
model1.linear1.weight

Parameter containing:
tensor([[ 0.1245, -0.2669, -0.0677,  0.2571, -0.1365],
        [-0.3157, -0.3222,  0.3951,  0.2610,  0.0552],
        [-0.3250,  0.2701,  0.2869, -0.2923,  0.3601]], requires_grad=True)

In [ ]:
model1.linear1.bias

Parameter containing:
tensor([-0.0948,  0.1078, -0.0229], requires_grad=True)

In [ ]:
model1.linear2.weight

Parameter containing:
tensor([[-0.3781, -0.2255,  0.2849]], requires_grad=True)

In [ ]:
model1.linear2.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model1)


Layer (type:depth-idx)                   Param #
Model1                                   --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=42)

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.long)
y_test_tensor=torch.tensor(y_test,dtype=torch.long)

In [ ]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super(MySimpleNN, self).__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()
  def forward(self, x):
    return self.sigmoid(self.linear(x))

In [ ]:
learning_rate=0.1
epochs=25

In [ ]:
model=MySimpleNN(X_train_tensor.shape[1])

for epoch in range(epochs):
  y_pred=model.forward(X_train_tensor)
  loss=nn.BCELoss()(y_pred,y_train_tensor.unsqueeze(1).float())
  optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.7007759809494019
Epoch: 2, Loss: 0.5440670251846313
Epoch: 3, Loss: 0.4581906199455261
Epoch: 4, Loss: 0.404609739780426
Epoch: 5, Loss: 0.36724069714546204
Epoch: 6, Loss: 0.3392362892627716
Epoch: 7, Loss: 0.3172053396701813
Epoch: 8, Loss: 0.29925885796546936
Epoch: 9, Loss: 0.28425201773643494
Epoch: 10, Loss: 0.2714459300041199
Epoch: 11, Loss: 0.2603399157524109
Epoch: 12, Loss: 0.25058141350746155
Epoch: 13, Loss: 0.24191386997699738
Epoch: 14, Loss: 0.23414567112922668
Epoch: 15, Loss: 0.2271302491426468
Epoch: 16, Loss: 0.22075343132019043
Epoch: 17, Loss: 0.21492457389831543
Epoch: 18, Loss: 0.2095707207918167
Epoch: 19, Loss: 0.20463232696056366
Epoch: 20, Loss: 0.20006023347377777
Epoch: 21, Loss: 0.19581323862075806
Epoch: 22, Loss: 0.19185666739940643
Epoch: 23, Loss: 0.1881609410047531
Epoch: 24, Loss: 0.1847006231546402
Epoch: 25, Loss: 0.18145360052585602


In [ ]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred_class=torch.where(y_pred>0.5,1,0)
  accuracy=(y_pred_class==y_test_tensor).sum().item()/len(y_test_tensor)
  print(f'Accuracy: {accuracy}')

Accuracy: 60.43859649122807
